---
- hosts: all
  become: yes
  user: root
  tasks:
    - name: Add root pub key
      authorized_key:
       user: root
       state: present
       key: "{{ lookup('file', './id_rsa.pub') }}"
    - name: Add host file entries
      blockinfile:
        path: /etc/hosts
        block: |
          {{ item.ip }} {{ item.name }}
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
      with_items:
        - { name: manager, ip: 192.168.56.201 }
        - { name: master, ip: 192.168.56.202 }
        - { name: node-a, ip: 192.168.56.203 }
        - { name: node-b, ip: 192.168.56.204 }
    - name: lvresize so you can actually install
      shell: lvresize --size=+3g --resizefs atomicos/root
    - name: enable epel-release repo
      shell: rpm-ostree pkg-add epel-release
    - name: restart server
      shell: sleep 2 && systemctl reboot
      async: 1
      poll: 0
      become: yes
      become_method: sudo
      ignore_errors: true
    - name: Pause for the cause
      pause: seconds=20
    - name: waiting for server to come back after reboot
      wait_for_connection:
    - name: uptime report
      command: uptime
      register: uptime
    - debug: var=uptime.stdout_lines
    - name: Install helper packages
      shell: atomic host install wget git net-tools bind-utils iptables-services bridge-utils bash-completion kexec-tools sos ansible pyOpenSSL
      ignore_errors: true
    - name: restart server
      shell: sleep 2 && systemctl reboot
      async: 1
      poll: 0
      become: yes
      become_method: sudo
      ignore_errors: true
